platform :ios, '12.0'
use_frameworks!

target 'Inyore' do
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~> 4.0'
  pod 'Alamofire', '~> 4.0'
  pod 'ObjectMapper'
  pod 'Socket.IO-Client-Swift', '~> 15.1.0'
  pod 'SideMenu'
  pod 'DropDown'
  pod 'NVActivityIndicatorView'
    
end
